### ISSUE TITLE
Not sure how to run

### ISSUE THREAD

**Issue by famattsson** [reunanen/openvslam-build-vs#2]
I'm not sure how to run this repository. I'm trying to run the run_camera_slam project but all that happens is that a console window pops for a fraction of a second and then disappears. I get logs saying that the PDB file cannot be found. How am I supposed to run this? Sorry if i'm missing something obvious.

**Comment by reunanen** [comment]
@famattsson I guess you just need to supply some command line arguments.

See:
* [Arguments supported by `run_camera_slam`](https://openvslam.readthedocs.io/en/master/example.html#id5)
* [How to set command line arguments when launching a program in Visual Studio](https://cs-people.bu.edu/deht/CS585/VSTutorial/#CommandLineArgs)

Note that you can also open a Command Prompt window, `cd` to `c:\openvslam-build-vs` (or wherever you cloned the repo to), and run `x64\Release\run_camera_slam` (with or without parameters).

**Comment by reunanen** [comment]
Also, you may want to try `run_video_slam` first. [Here you can find detailed instructions](https://openvslam.readthedocs.io/en/master/simple_tutorial.html), complete with the required command line arguments. The instructions should be easy enough to adapt to Windows.

**Comment by famattsson** [comment]
Thanks, I got it to work
