### ISSUE TITLE
Something wrong in the vocabulary file

### ISSUE THREAD

**Issue by CJCHEN1230** [reunanen/openvslam-build-vs#4]
Thanks for organizing Visual Studio version. It's really helpful!
I have some problem when the code run to "loadFromBinaryFile", it got a huge number of node(like 55824124).  And the program would crash when allocating memory for these nodes. I think the problem comes from data format between different operating system. However, after modifying the control character problem(LF-CRLF). It still doesn't work.  Am i missing something?

**Comment by reunanen** [comment]
Sorry, I have no idea.

But to help anybody to help you, would you at least put together a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by reunanen** [comment]
Sorry, I have no idea.

But to help anybody help you, would you at least put together a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by CJCHEN1230** [comment]
Thanks for reply.
I execute "run_video_localization" in VS2017 with following input argument:
-v path\orb_vocab.fbow 
-c path\CRLF_equirectangular.yaml 
-m path\video.mp4 
--frame-skip 3 --map-db aist_living_lab_1_map.msg

However, the number of nodes is too large, raise an exception shows that the vector is too long.
![image](https://user-images.githubusercontent.com/22461372/143375649-14198657-9d66-4a30-a93a-76f15dab2be7.png)

I thought the format  of vocabulary from fbow and Dbow2 are different, but both files cause the same problem.

**Comment by reunanen** [comment]
Looking at the screenshot (and only that), it seems that there is no check that reading the file succeeded in the first place.

What if you initialize `n_nodes` to 0? Does it stay at 0 after the `ifs.read` call?

You could also check that `ifs.read` succeeds. If not, then the function should really just error out.

**Comment by CJCHEN1230** [comment]
Finally, I solve the problem. The vocabulary I download for DBoW2 is a text file. I convert  it into binary by following code and it work.  I mistakenly thought the vocabulary from DBow2 and fBow is compatible. 
```
bow_vocab_->loadFromTextFile(vocab_file_path);
bow_vocab_->saveToBinaryFile(".\\fbow_binary");
```
Thanks again for answering my question.
