### ISSUE TITLE
Poor Track Time 

### ISSUE THREAD

**Issue by SimonLisowski** [reunanen/openvslam-build-vs#5]
Hello! Thank you for this repo, it's been very helpful.

I've installed with the instructions and got both a `run_video_slam` example and `run_camera_slam` working, but I'm getting some very poor track times with the default config file in both of these cases, ~1500ms per frame with 2000 keypoints. This goes down to ~800ms per frame at 500 keypoints, so still very poor. This is at an already scaled-down resolution of 960x480. Do you have any idea what the reason for this could be?

I'm running on Intel i7 11800H. The ORB parameters are as follows:

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

**Comment by reunanen** [comment]
> Do you have any idea what the reason for this could be?

Sorry, not really – I'm no longer working with any of this stuff.

Unfortunately the original OpenVSLAM project has been [terminated](https://github.com/xdspacelab/openvslam/wiki/Termination-of-the-release), as you probably know. So I guess it might be advisable to use some other library for which somebody is available to answer questions.

**Comment by SimonLisowski** [comment]
No worries, thank you for the response.
